### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by real-ljt** [XsLangley/TDGAN#1]
When will the code be available?

**Comment by XsLangley** [comment]
Sorry, I am busy these days. I plan to release the code in one month. If I forget it, please remind me...

**Comment by real-ljt** [comment]
Hey, is the code available now?

**Comment by XsLangley** [comment]
Hi, I am reorganizing the code and I think a preliminary (but maybe a little bit messy) version can be released in a few days.
Thanks a lot for your reminder:)
