### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by myt889** [XsLangley/TDGAN#2]
Hi, I have read your paper. Now I am trying to train  an entire TDGAN from scratch,but I find it is so slowly,maybe one weak for 40 epchs.How long does it take to train for CASIA-WebFace and RAF-DBE datasets in your experiment? 
![40_300](https://user-images.githubusercontent.com/77277761/113651916-732d3b80-96c5-11eb-8353-01245de5ea3c.jpg)
Fig 1. 40_300.jpg

If I have made any mistakes, thank you for your corrections.

**Comment by XsLangley** [comment]
Thanks a lot for your comment. 
I remember that it took me about 6 hours to run 120 epochs by training from scratch (face dataset: the first 20 classes of casia-webface; expression dataset: RAF-DB ). 
The machine I used to train it is configured with a Titan X GPU card and two Intel Xeon CPU (but I forget which version of Xeon, maybe E5-2679).

**Comment by XsLangley** [comment]
> Hi, I have read your paper. Now I am trying to train an entire TDGAN from scratch,but I find it is so slowly,maybe one weak for 40 epchs.How long does it take to train for CASIA-WebFace and RAF-DBE datasets in your experiment?
> ![40_300](https://user-images.githubusercontent.com/77277761/113651916-732d3b80-96c5-11eb-8353-01245de5ea3c.jpg)
> Fig 1. 40_300.jpg
> 
> If I have made any mistakes, thank you for your corrections.

Thanks a lot for your comment.
I remember that it took me about 6 hours to run 120 epochs by training from scratch (face dataset: the first 20 classes of casia-webface; expression dataset: RAF-DB ).
The machine I used to train it is configured with a Titan X GPU card and two Intel Xeon CPU (but I forget which version of Xeon, maybe E5-2679).

**Comment by myt889** [comment]
Thank you for your work, I have solved the problem.
